swagger: "2.0"
info: {}
basePath: /fabric
paths:
  /chaincode/ChaincodeInfo:
    post:
      tags:
      - chaincode
      description: ChaincodeInfo chaincode on peers
      operationId: ChaincodeController.ChaincodeInfo
      parameters:
      - in: body
        name: body
        description: body for chaincode Description
        required: true
        schema:
          $ref: '#/definitions/chaincode.ChaincodeInfoArgs'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /chaincode/InstallCC:
    post:
      tags:
      - chaincode
      description: InstallCC on peers
      operationId: ChaincodeController.InstallCC
      parameters:
      - in: body
        name: body
        description: body for chaincode Description
        required: true
        schema:
          $ref: '#/definitions/chaincode.InstallCCArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
  /chaincode/InstantiateCC:
    post:
      tags:
      - chaincode
      description: Instantiate chaincode on peers
      operationId: ChaincodeController.InstantiateCC
      parameters:
      - in: body
        name: body
        description: body for chaincode Description
        required: true
        schema:
          $ref: '#/definitions/chaincode.InstantiateArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
  /chaincode/InvokeCC:
    post:
      tags:
      - chaincode
      description: Invoke chaincode on peers
      operationId: ChaincodeController.InvokeCC
      parameters:
      - in: body
        name: body
        description: body for chaincode Description
        required: true
        schema:
          $ref: '#/definitions/chaincode.InvokeArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
  /chaincode/QueryCC:
    post:
      tags:
      - chaincode
      description: Query chaincode on peers
      operationId: ChaincodeController.QueryCC
      parameters:
      - in: body
        name: body
        description: body for chaincode Description
        required: true
        schema:
          $ref: '#/definitions/chaincode.QueryArgs'
      responses:
        "200":
          description: '{string} txId'
        "403":
          description: body is empty
  /channel/CreateChannel:
    post:
      tags:
      - channel
      description: ChannelCreate on peers
      operationId: ChannelController.ChannelCreate
      parameters:
      - in: body
        name: body
        description: body for ChannelCreate Description
        required: true
        schema:
          $ref: '#/definitions/channel.ChannelCreateArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
  /channel/JoinChannel:
    post:
      tags:
      - channel
      description: ChannelJoin on peers
      operationId: ChannelController.ChannelJoin
      parameters:
      - in: body
        name: body
        description: body for ChannelJoin Description
        required: true
        schema:
          $ref: '#/definitions/channel.ChannelJoinArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
  /query/QueryBlock:
    post:
      tags:
      - query
      description: Query Block
      operationId: QueryController.QueryBlock
      parameters:
      - in: body
        name: body
        description: body for Query Block
        required: true
        schema:
          $ref: '#/definitions/query.QueryBlockArgs'
      responses:
        "200":
          description: '{string} []string'
        "403":
          description: body is empty
  /query/QueryChainInfo:
    post:
      tags:
      - query
      description: Query Chain Info
      operationId: QueryController.QueryChainInfo
      parameters:
      - in: body
        name: body
        description: body for Query BlockChain Info
        required: true
        schema:
          $ref: '#/definitions/query.QueryChainInfoArgs'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /query/QueryChannels:
    post:
      tags:
      - query
      description: Query Channels
      operationId: QueryController.QueryChannels
      parameters:
      - in: body
        name: body
        description: body for Query Channel
        required: true
        schema:
          $ref: '#/definitions/query.QueryChannelsArgs'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /query/QueryInstalledChaincodes:
    post:
      tags:
      - query
      description: Query Chaincodes installed on the peerUrl
      operationId: QueryController.QueryInstalledChaincodes
      parameters:
      - in: body
        name: body
        description: body for Query Installed Chaincode Info
        required: true
        schema:
          $ref: '#/definitions/query.QueryInstalledArgs'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: body is empty
  /query/QueryTx:
    post:
      tags:
      - query
      description: query transaction
      operationId: QueryController.QueryTx
      parameters:
      - in: body
        name: body
        description: body for querytx Description
        required: true
        schema:
          $ref: '#/definitions/query.QueryTxArgs'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
definitions:
  chaincode.ChaincodeInfoArgs:
    title: ChaincodeInfoArgs
    type: object
    properties:
      chaincodeId:
        type: string
      channelId:
        type: string
      peerUrl:
        type: string
  chaincode.InstallCCArgs:
    title: InstallCCArgs
    type: object
    properties:
      chaincodeID:
        type: string
      chaincodePath:
        type: string
      chaincodeVersion:
        type: string
      channelID:
        type: string
      peerUrl:
        type: string
  chaincode.InstantiateArgs:
    title: InstantiateArgs
    type: object
    properties:
      args:
        type: array
        items:
          type: string
      chaincodeID:
        type: string
      chaincodePath:
        type: string
      chaincodeVersion:
        type: string
      channelID:
        type: string
      peerUrl:
        type: string
  chaincode.InvokeArgs:
    title: InvokeArgs
    type: object
    properties:
      args:
        type: array
        items:
          type: string
      chaincodeId:
        type: string
      channelId:
        type: string
      peerUrl:
        type: string
  chaincode.QueryArgs:
    title: QueryArgs
    type: object
    properties:
      args:
        type: array
        items:
          type: string
      chaincodeId:
        type: string
      channelID:
        type: string
      peerUrl:
        type: string
  channel.ChannelCreateArgs:
    title: ChannelCreateArgs
    type: object
    properties:
      channelId:
        type: string
      ordererUrl:
        type: string
      txFile:
        type: string
  channel.ChannelJoinArgs:
    title: ChannelJoinArgs
    type: object
    properties:
      channelId:
        type: string
      ordererUrl:
        type: string
      peerUrl:
        type: string
  query.QueryBlockArgs:
    title: QueryBlockArgs
    type: object
    properties:
      blockHash:
        type: string
      blockNum:
        type: string
      channelId:
        type: string
      peerUrl:
        type: string
      traverse:
        type: string
  query.QueryChainInfoArgs:
    title: QueryChainInfoArgs
    type: object
    properties:
      channelId:
        type: string
      peerUrl:
        type: string
  query.QueryChannelsArgs:
    title: QueryChannelsArgs
    type: object
    properties:
      peerUrl:
        type: string
  query.QueryInstalledArgs:
    title: QueryInstalledArgs
    type: object
    properties:
      peerUrl:
        type: string
  query.QueryTxArgs:
    title: QueryTxArgs
    type: object
    properties:
      channelId:
        type: string
      peerUrl:
        type: string
      txId:
        type: string
tags:
- name: channel
  description: |
    Operations about ChannelCreate
- name: chaincode
  description: |
    Operations about ChaincodeInfo
- name: query
  description: |
    Operations about QueryBlock
