swagger: "2.0"
info: {}
basePath: /fabric
paths:
  /user/:
    post:
      tags:
      - user
      description: create users
      operationId: UserController.CreateUser
      parameters:
      - in: body
        name: body
        description: body for user content
        required: true
        schema:
          $ref: '#/definitions/user.User'
      responses:
        "200":
          description: '{int} user.User.Id'
        "403":
          description: body is empty
  /user/{name}:
    get:
      tags:
      - user
      description: get user by name
      operationId: UserController.Get
      parameters:
      - in: path
        name: name
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/user.User'
        "403":
          description: :name is empty
  /user/{uid}:
    put:
      tags:
      - user
      description: update the user
      operationId: UserController.Update
      parameters:
      - in: path
        name: uid
        description: The uid you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for user content
        required: true
        schema:
          $ref: '#/definitions/user.User'
      responses:
        "200":
          schema:
            $ref: '#/definitions/user.User'
        "403":
          description: :uid is not int
  /user/login:
    get:
      tags:
      - user
      description: Logs user into the system
      operationId: UserController.Login
      parameters:
      - in: query
        name: username
        description: The username for login
        required: true
        type: string
      - in: query
        name: password
        description: The password for login
        required: true
        type: string
      responses:
        "200":
          description: '{string} login success'
        "403":
          description: user not exist
  /user/logout:
    get:
      tags:
      - user
      description: Logs out current logged in user session
      operationId: UserController.logout
      responses:
        "200":
          description: '{string} logout success'
definitions:
  user.User:
    title: User
    type: object
    properties:
      id:
        type: integer
        format: int64
      mail:
        type: string
      name:
        type: string
      passwd:
        type: string
      phone:
        type: string
      type:
        type: integer
        format: int64
tags:
- name: user
  description: |
    Operations about Users
