swagger: "2.0"
info:
  title: beego  API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: warm3snow@linux.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /fabric
paths:
  /enroll/:
    post:
      tags:
      - enroll
      description: Get Key and Ecert
      operationId: EnrollController.Enroll
      parameters:
      - in: body
        name: body
        description: body for Ecert content
        required: true
        schema:
          $ref: '#/definitions/cert.EnrollReq'
      responses:
        "200":
          description: '{string}'
        "403":
          description: body is empty
definitions:
  cert.EnrollReq:
    type: object
tags:
- name: enroll
  description: |
    Operations about Enroll
